# -*- coding: utf-8 -*-
"""AI_Text_Generator_GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PMpFMxoU4ydPxkmKvleDGELGr1P0OXA

#**AI Text Generator using GPT**

# Objective
To develop a generative AI model capable of producing coherent paragraphs based on user prompts using OpenAI GPT-2 architecture.

# Technologies Used
- Python
- Hugging Face Transformers
- GPT-2
- Google Colab
- PyTorch

# Features
- User prompt based generation
- Multiple paragraph generation
- Adjustable creativity using temperature
- Real-time text synthesis

# Workflow

1. **Dataset Collection**  
   A text dataset containing AI, technology, healthcare, cybersecurity, and machine learning related sentences was created and used for training the LSTM model.

2. **Text Preprocessing**  
   The dataset was preprocessed using tokenization and sequence generation techniques. Text sentences were converted into numerical sequences suitable for deep learning models.

3. **Sequence Padding**  
   Padding techniques were applied to ensure all input sequences had equal length for efficient model training and prediction.

4. **LSTM Model Development**  
   An LSTM-based deep learning model was designed using embedding, LSTM, and dense layers to learn sequential text patterns and predict the next probable words.

5. **LSTM Model Training**  
   The LSTM architecture was trained on the prepared dataset for multiple epochs to improve sequence learning and text generation capability.

6. **GPT-2 Transformer Integration**  
   A pretrained GPT-2 transformer model was integrated using the Hugging Face Transformers library for advanced context-aware text generation.

7. **Prompt-Based Text Generation**  
   User-defined prompts were provided as input to both LSTM and GPT-2 models for generating meaningful and coherent text outputs.

8. **Creativity Control Implementation**  
   Multiple generation modes such as Creative, Balanced, and Precise were implemented using temperature-based text generation control.

9. **Comparative Analysis**  
   The outputs generated by LSTM and GPT-2 were compared based on contextual understanding, fluency, coherence, scalability, and overall performance.

10. **Interactive User Interface Development**  
    A Gradio-based web interface was developed to provide real-time interaction and dynamic AI text generation capabilities.

11. **Result Evaluation**  
    The generated outputs were evaluated to analyze the effectiveness of sequential and transformer-based architectures for Generative AI applications.

12. **Final Deployment and Demonstration**  
    The complete AI-powered text generation system was executed and demonstrated as an interactive Generative AI application.
"""

!pip install transformers torch accelerate -q

!pip install tensorflow transformers torch accelerate gradio -q

!pip install tensorflow numpy -q

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

from transformers import pipeline

import warnings
warnings.filterwarnings('ignore')

data = """
Artificial Intelligence is transforming industries worldwide and improving automation.
Machine learning enables intelligent systems to learn patterns from historical data.
Deep learning models are widely used in computer vision and speech recognition.
Natural language processing helps computers understand and generate human language.
Generative AI can create realistic text, images, and digital content efficiently.
Cyber security protects computer systems and sensitive information from cyber attacks.
Cloud computing provides scalable and flexible computing resources over the internet.
Data science helps organizations analyze data and make informed business decisions.
Modern AI applications are revolutionizing healthcare, education, and finance sectors.
Robotics and artificial intelligence are shaping the future of smart industries.
The future of artificial intelligence includes advanced automation and intelligent systems.
AI powered virtual assistants improve customer interaction and communication services.
Game development combines programming, graphics, storytelling, and artificial intelligence.
Technology innovation is driving digital transformation across multiple industries.
Artificial intelligence enhances productivity and supports decision making processes.
"""

# Create tokenizer object
tokenizer = Tokenizer()

# Fit tokenizer on dataset
tokenizer.fit_on_texts([data])

# Count total unique words
total_words = len(tokenizer.word_index) + 1

# Store all input sequences
input_sequences = []

# Process dataset line by line
for line in data.split('.'):

    # Convert sentence into tokens
    token_list = tokenizer.texts_to_sequences([line])[0]

    # Generate n-gram sequences
    for i in range(1, len(token_list)):

        # Create sequential token pattern
        n_gram_sequence = token_list[:i+1]

        # Append sequence to list
        input_sequences.append(n_gram_sequence)

# Find maximum sequence length
max_sequence_len = max([len(x) for x in input_sequences])

# Apply padding to all sequences
input_sequences = np.array(

    pad_sequences(
        input_sequences,
        maxlen=max_sequence_len,
        padding='pre'
    )
)

# Separate input features and labels
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

# Convert labels into categorical format
y = tf.keras.utils.to_categorical(
    y,
    num_classes=total_words
)

# Create Sequential deep learning model
lstm_model = Sequential()

# Add embedding layer
lstm_model.add(

    Embedding(
        input_dim=total_words,
        output_dim=128,
        input_length=max_sequence_len - 1
    )
)

# Add LSTM layer
lstm_model.add(LSTM(256))

# Add output layer
lstm_model.add(

    Dense(
        total_words,
        activation='softmax'
    )
)

# Compile model
lstm_model.compile(

    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Build model manually
lstm_model.build(input_shape=(None, max_sequence_len - 1))

# Show model summary
lstm_model.summary()

history = lstm_model.fit(

    X,
    y,

    epochs=500,

    verbose=1
)

# Function for generating text using the trained LSTM model

def generate_lstm_text(seed_text, next_words):

    # Generate words one by one
    for _ in range(next_words):

        # Convert input sentence into token sequence
        token_list = tokenizer.texts_to_sequences([seed_text])[0]

        # Apply padding to maintain equal sequence length
        token_list = pad_sequences(

            [token_list],

            # Define maximum sequence length
            maxlen=max_sequence_len - 1,

            # Add padding before sequence
            padding='pre'
        )

        # Predict the next probable word
        predicted = np.argmax(

            lstm_model.predict(

                token_list,

                # Hide prediction progress bar
                verbose=0
            ),

            axis=-1
        )

        # Initialize output word
        output_word = ""

        # Find actual word corresponding to predicted index
        for word, index in tokenizer.word_index.items():

            if index == predicted:

                output_word = word
                break

        # Append predicted word to input sentence
        seed_text += " " + output_word

    # Return final generated sentence
    return seed_text

# Import transformers logging
from transformers.utils import logging

# Hide unnecessary warnings
logging.set_verbosity_error()

# Load pretrained GPT-2 model
gpt2_generator = pipeline(

    "text-generation",

    model="gpt2"
)

# Take topic input from user
user_prompt = input("Enter Your Topic: ")

# Display LSTM heading
print("\n==============================")
print("LSTM GENERATED TEXT")
print("==============================\n")

# Generate text using LSTM
lstm_output = generate_lstm_text(
    user_prompt,
    20
)

# Print LSTM output
print(lstm_output)

# Display GPT-2 heading
print("\n==============================")
print("GPT-2 GENERATED TEXT")
print("==============================\n")

# Generate text using GPT-2
gpt2_output = gpt2_generator(

    user_prompt,

    # Maximum output length
    max_new_tokens=120,

    # Generate one output sequence
    num_return_sequences=1,

    # Creativity control parameter
    temperature=0.8
)

# Print GPT-2 generated text
print(gpt2_output[0]['generated_text'])

# Take creativity level input from user
temperature_value = float(

    input("Enter Creativity Level (0.1 - 1.0): ")
)

# Generate advanced GPT-2 outputs
advanced_output = gpt2_generator(

    user_prompt,

    # Output text length
    max_length=150,

    # Creativity parameter
    temperature=temperature_value,

    # Generate multiple outputs
    num_return_sequences=2
)

# Display generated paragraphs
for i, text in enumerate(advanced_output):

    print(f"\nGenerated Paragraph {i+1}:\n")

    print(text['generated_text'])

# Import Gradio library
import gradio as gr

# Define text generation function
def generate_text(prompt, mode):

    # Set temperature according to selected mode
    if mode == "Creative":
        temperature = 1.0

    elif mode == "Balanced":
        temperature = 0.7

    else:
        temperature = 0.3

    # Generate text using GPT-2
    gpt_output = gpt2_generator(

        prompt,

        # Generate output length
        max_new_tokens=80,

        # Creativity control
        temperature=temperature,

        # Reduce repetition
        repetition_penalty=1.5,

        # Enable sampling
        do_sample=True,

        # Top-k sampling
        top_k=50,

        # Top-p nucleus sampling
        top_p=0.95,

        # Generate one output
        num_return_sequences=1
    )

    # Return generated text
    return gpt_output[0]['generated_text']


# Create Gradio interface
interface = gr.Interface(

    fn=generate_text,

    # Inputs
    inputs=[

        gr.Textbox(
            lines=2,
            placeholder="Enter your topic here...",
            label="Topic"
        ),

        gr.Dropdown(

            choices=[
                "Creative",
                "Balanced",
                "Precise"
            ],

            value="Balanced",

            label="Generation Mode"
        )
    ],

    # Output textbox
    outputs=gr.Textbox(

        lines=10,

        label="Generated Text"
    ),

    # Interface title
    title="AI Text Generator using GPT-2",

    # Interface description
    description="""
    Generate intelligent and context-aware paragraphs using GPT-2 Transformer Model.

    Modes:
    - Creative → More imaginative outputs
    - Balanced → Professional balanced text
    - Precise → Focused and deterministic responses
    """
)

# Launch the interface
interface.launch()

"""# Comparative Analysis

| Feature | LSTM | GPT-2 |
|---|---|---|
| Architecture | Recurrent Neural Network (RNN) | Transformer Architecture |
| Learning Mechanism | Sequential Memory-Based Learning | Self-Attention Mechanism |
| Context Understanding | Limited Long-Term Context Handling | Strong Contextual Understanding |
| Text Quality | Moderate and Sequential | Fluent and Human-Like |
| Training Requirement | Requires Custom Dataset Training | Uses Large Pretrained Knowledge |
| Computational Complexity | Lower | Higher |
| Scalability | Limited for Large-Scale NLP Tasks | Highly Scalable |
| Speed on Small Dataset | Faster | Slightly Slower |
| Handling Long Sequences | Less Efficient | Highly Efficient |
| Industry Usage | Traditional NLP Applications | Modern Generative AI Systems |
| Output Coherence | Moderate | Advanced and Context-Aware |
| Real-World Applications | Basic Text Prediction | Chatbots, Content Generation, AI Assistants |
| Overall Performance | Good for Learning Sequential Models | Superior for Advanced NLP Tasks |

---

# Technologies Used

- Python
- TensorFlow
- Keras
- Hugging Face Transformers
- GPT-2
- LSTM
- Gradio
- Google Colab

# Future Work

Future enhancements of this project may include fine-tuning GPT-2 on large domain-specific datasets such as healthcare, finance, education, or cybersecurity to generate more specialized and accurate content. The implementation can also be extended using advanced transformer architectures such as GPT-Neo, LLaMA, or Mistral models for improved contextual understanding and higher-quality text generation.

Additional improvements may involve integrating multilingual text generation, sentiment-aware responses, speech-to-text interaction, and real-time conversational memory systems to create more intelligent and interactive AI assistants. The system can further be deployed as a scalable web application using cloud platforms and optimized for mobile and edge devices to support real-world production environments.

Moreover, future research may focus on reducing computational complexity, improving ethical AI generation, minimizing biased outputs, and implementing reinforcement learning based optimization techniques for more adaptive and human-centric text generation systems.

# Conclusion

This project successfully demonstrates the design, implementation, and comparative evaluation of two advanced text generation architectures: Long Short-Term Memory (LSTM) networks and the GPT-2 transformer model. The developed system was capable of generating coherent, context-aware, and human-like text dynamically from user-defined prompts, highlighting the practical capabilities of modern Generative Artificial Intelligence and Natural Language Processing technologies.

The LSTM model provided a strong foundation for understanding sequential learning and recurrent neural network based text prediction, whereas GPT-2 achieved significantly superior performance through transformer architecture and self-attention mechanisms, enabling more fluent, contextually rich, and semantically meaningful text generation. The comparative analysis clearly illustrated the advancement of transformer-based models over traditional recurrent architectures in modern NLP applications.

Furthermore, the integration of an interactive Gradio-based user interface enhanced the practical usability of the project by enabling real-time prompt-based text generation with customizable generation modes such as Creative, Balanced, and Precise outputs. This feature transformed the implementation from a simple deep learning experiment into a functional AI-powered application.

Overall, the project provided comprehensive hands-on exposure to Deep Learning, Sequential Modeling, Transformer Architectures, Prompt Engineering, and Generative AI systems. The implementation demonstrates how advanced language models can be effectively utilized in real-world domains including healthcare, education, intelligent virtual assistants, automated content generation, robotics, and smart digital systems, making the project a strong practical application of state-of-the-art Artificial Intelligence technologies.
"""